name: clean-renv

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove renv activate for package deployment
      run: |
        if grep source\(\"renv/activate.R\"\) .Rprofile;then echo "renv is activated in .Rprofile - removing";fi
        if grep source\(\"renv/activate.R\"\) .Rprofile;then sed -i '/source("renv/activate.R")/d' .Rprofile;fi
    - name: Commit Changes
      run: |
        git config --global user.name "action@github.com"
        git config --global user.email "Github Action"
        git add .Rprofile
        git commit -m "remove renv activate from rprofile"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
